// <auto-generated />
using System;
using Look;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Look.Migrations
{
    [DbContext(typeof(LookContext))]
    [Migration("20210113105550_AddLikedTable")]
    partial class AddLikedTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Look.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikersNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AchterNaam")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EmailAdres")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("GebruikersNaam")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HuisNummer")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsAnoniem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsGeverifieerd")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LoginPogingen")
                        .HasColumnType("int");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VoorNaam")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WachtWoord")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GebruikersNummer");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("Look.Models.Liked", b =>
                {
                    b.Property<long>("LikedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("GebruikersNummer")
                        .HasColumnType("int");

                    b.Property<long>("MeldingId")
                        .HasColumnType("bigint");

                    b.Property<bool>("heeftGeliked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("LikedId");

                    b.ToTable("Liked");
                });

            modelBuilder.Entity("Look.Models.Melding", b =>
                {
                    b.Property<long>("MeldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AuteurGebruikersNummer")
                        .HasColumnType("int");

                    b.Property<string>("Categorie")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Inhoud")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActief")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("MeldingId");

                    b.HasIndex("AuteurGebruikersNummer");

                    b.ToTable("Meldingen");
                });

            modelBuilder.Entity("Look.Models.Reactie", b =>
                {
                    b.Property<long>("ReactieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Bericht")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("GeplaatstDoorGebruikersNummer")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeplaatstOp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<long?>("MeldingId")
                        .HasColumnType("bigint");

                    b.HasKey("ReactieId");

                    b.HasIndex("GeplaatstDoorGebruikersNummer");

                    b.HasIndex("MeldingId");

                    b.ToTable("Reacties");
                });

            modelBuilder.Entity("Look.Models.Melding", b =>
                {
                    b.HasOne("Look.Models.Gebruiker", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurGebruikersNummer");

                    b.Navigation("Auteur");
                });

            modelBuilder.Entity("Look.Models.Reactie", b =>
                {
                    b.HasOne("Look.Models.Gebruiker", "GeplaatstDoor")
                        .WithMany()
                        .HasForeignKey("GeplaatstDoorGebruikersNummer");

                    b.HasOne("Look.Models.Melding", null)
                        .WithMany("Reacties")
                        .HasForeignKey("MeldingId");

                    b.Navigation("GeplaatstDoor");
                });

            modelBuilder.Entity("Look.Models.Melding", b =>
                {
                    b.Navigation("Reacties");
                });
#pragma warning restore 612, 618
        }
    }
}
